import { Routes } from '@angular/router';
import { AssumptionsSlideComponent } from './01-assumptions/assumptions-slide.component';
import { UseCaseSlideComponent } from './02-use-case/use-case-slide.component';
import { TemplateFormsSlideComponent } from './03-template-forms/template-forms-slide.component';
import { ReactiveFormsSlideComponent } from './04-reactive-forms/reactive-forms-slide.component';
import { ComparisonSlideComponent } from './05-comparison/comparison-slide.component';
import { SignalsSlideComponent } from './06-signals/signals-slide.component';
import { SignalFormsSlideComponent } from './07-signal-forms/signal-forms-slide.component';
import { SignalFormsApiSlideComponent } from './08-signal-forms-api/signal-forms-api-slide.component';
import { CvaSlideComponent } from './09-cva/cva-slide.component';
import { FeatureMappingSlideComponent } from './10-feature-mapping/feature-mapping-slide.component';
import { DemoSlideComponent } from './11-demo/demo-slide.component';
import { PerformanceSlideComponent } from './12-performance/performance-slide.component';
import { PerformanceComparisonSlideComponent } from './13-performance-comparison/performance-comparison-slide.component';
import { LatestPerformanceSlideComponent } from './14-latest-performance/latest-performance-slide.component';
import { BundleSizeSlideComponent } from './15-bundle-size/bundle-size-slide.component';
import { LearningCurveSlideComponent } from './16-learning-curve/learning-curve-slide.component';
import { CommunitySlideComponent } from './17-community/community-slide.component';
import { WhenToUseSlideComponent } from './18-when-to-use/when-to-use-slide.component';
import { ZonelessSlideComponent } from './19-zoneless/zoneless-slide.component';
import { MigrationSlideComponent } from './20-migration/migration-slide.component';
import { ThankYouSlideComponent } from './21-thank-you/thank-you-slide.component';

export const slidesRoutes: Routes = [
  { path: '', redirectTo: '1', pathMatch: 'full' },
  { path: '1', component: AssumptionsSlideComponent },
  { path: '2', component: UseCaseSlideComponent },
  { path: '3', component: TemplateFormsSlideComponent },
  { path: '4', component: ReactiveFormsSlideComponent },
  { path: '5', component: ComparisonSlideComponent },
  { path: '6', component: SignalsSlideComponent },
  { path: '7', component: SignalFormsSlideComponent },
  { path: '8', component: SignalFormsApiSlideComponent },
  { path: '9', component: CvaSlideComponent },
  { path: '10', component: FeatureMappingSlideComponent },
  { path: '11', component: DemoSlideComponent },
  { path: '12', component: PerformanceSlideComponent },
  { path: '13', component: PerformanceComparisonSlideComponent },
  { path: '14', component: LatestPerformanceSlideComponent },
  { path: '15', component: BundleSizeSlideComponent },
  { path: '16', component: LearningCurveSlideComponent },
  { path: '17', component: CommunitySlideComponent },
  { path: '18', component: WhenToUseSlideComponent },
  { path: '19', component: ZonelessSlideComponent },
  { path: '20', component: MigrationSlideComponent },
  { path: '21', component: ThankYouSlideComponent },
  { path: '**', redirectTo: '1' }
];
